version: 2.1
jobs:
  testwindows:
    executor: windows-tools/default
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Invoke-Pester"
          shell: powershell.exe -ExecutionPolicy Bypass
          command: |
            $PSVersionTable
            Install-Module pester -force -verbose -requiredversion '5.2.0'
            Install-Module PSScriptAnalyzer -force -verbose
            Invoke-Pester -CI -Output Detailed
  testlinux:
    docker:
      - image: mcr.microsoft.com/powershell:latest
    steps:
      - checkout
      - run:
          name: "Invoke-Pester"
          shell: pwsh
          command: |
            $PSVersionTable
            Install-Module Pester -force -verbose -requiredversion '5.2.0'
            Install-Module PSScriptAnalyzer -force -verbose
            Invoke-Pester -CI -Output Detailed
  deploy:
    executor: windows-tools/default
    steps:
      - checkout
      - run:
          name: "Deploy to gallery"
          shell: powershell.exe -ExecutionPolicy Bypass
          command: |
            $PSVersionTable
            # TO BE COMPLETED
workflows:
  version: 2
  pipeline:
    jobs:
      - testwindows:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - testlinux:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          filters:
            branches:
              only: /.master/
orbs:
  windows-tools: circleci/windows@2.2.0
